name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.push-tag.outputs.tag}}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label


      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{steps.get-latest-tag.outputs.tag}}
          level: 'patch' # ${{steps.release-label.outputs.level}}

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{steps.bump-semver.outputs.new_version}}
          message: '${{steps.bump-semver.outputs.new_version}}: \n PR #${{github.event.pull_request.number}} ${{github.event.pull_request.title}}'
        
      - name: get-latest-tag
        run: echo "Latest tag is ${{steps.get-latest-tag.outputs.tag}}"
          
  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Print ref name
        run: |
          echo "branch: ${{github.ref_name}}"
          echo "github.ref: ${{github.ref}}"
          echo "tag: ${{needs.release.outputs.tag}}"

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{github.token}}
          tag: ${{needs.release.outputs.tag}}
          writeToFile: true

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{github.ref_name}}
          body: ${{steps.changelog.outputs.changes}}
          token: ${{github.token}}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{github.ref_name}} [skip ci]'
          file_pattern: CHANGELOG.md